### ISSUE TITLE
Missing dependencies in ebuild

### ISSUE THREAD

**Issue by Diewi** [hartwork/update-notifier-tray#1]
I know, that this is not the correct place to note this issue, but its an easy to fix one anyways ;)

The ebuild in beta garden is missing two dependencies: pyside and notifier-daemon (the virtual one did not pull in x11-notifier-daemon, so I must have had some use flag wrong...).

**Comment by hartwork** [comment]
> The ebuild in beta garden is missing two dependencies: pyside and notifier-daemon

Good point.

> (the virtual one did not pull in x11-notifier-daemon, so I must have had some use flag wrong...).

The `virtual/notification-daemon-0` ebuild reads

```
RDEPEND="
        gnome? ( || ( x11-misc/notification-daemon
                gnome-base/gnome-shell ) )
        !gnome? ( || (
                x11-misc/notification-daemon
                gnome-extra/cinnamon
                xfce-extra/xfce4-notifyd
                x11-misc/qtnotifydaemon
                x11-misc/notify-osd
                x11-misc/dunst
                >=x11-wm/awesome-3.4.4
                x11-wm/enlightenment[enlightenment_modules_notification]
                x11-wm/enlightenment[e_modules_notification]
                kde-apps/knotify
                x11-misc/mate-notification-daemon
                lxqt-base/lxqt-notificationd
                kde-frameworks/knotifications ) )"
```

so if `x11-misc/notification-daemon` was not pulled in, I suppose you have one of the others installed already?

**Comment by hartwork** [comment]
1.2 added to betagarden now.

```
# diff -u update-notifier-tray-1.1.ebuild update-notifier-tray-1.2.ebuild
--- update-notifier-tray-1.1.ebuild     2015-09-14 19:00:48.494997291 +0200
+++ update-notifier-tray-1.2.ebuild     2015-10-24 22:30:31.271147695 +0200
@@ -17,8 +17,10 @@
 IUSE=""

 RDEPEND="
+       dev-python/pyside
        sys-apps/lsb-release
        sys-apps/portage
+       virtual/notification-daemon
        x11-themes/tango-icon-theme
        x11-terms/terminator
        "
```

I'm happy to further improve dependencies if needed. Please re-open in that case.

Thanks and best, Sebastian

**Comment by Diewi** [comment]
Thanks, I have knotifications installed which apparently satisfies the virtual. For some reason, the tray icon only appeared when emerging x11-misc/notification-daemon. Must be some problem with plasma 5 ...
