### ISSUE TITLE
Wrong update number

### ISSUE THREAD

**Issue by Diewi** [hartwork/update-notifier-tray#2]
Immediately after launching the application, it shows me that there are 9999 updates available, a number which does not change. Obviously, the number is to high ;)

I have no clue about the cause yet :)

Nevertheless, thanks for your efforts :)

**Comment by hartwork** [comment]
> I have no clue about the cause yet :)

My guess would be that emerge stopped due to a blocking situation.

Should be fixed by commit 0bc2a723dd4c4c73a5f310aa61ac0348a750a6aa, closing.

Thanks for the report!

**Comment by Diewi** [comment]
Thanks, issue is solved (no more 9999 packages to update). Nevertheless, this issue was due to some permission problems with my make.conf file that made it unreadable for my normal user. Solved it by moving the sensitive part to a separate file and using acls for this file.
